#执行时需要将这个文件调整为 config.yml
tutake:
  data:
    dir: ~/.tutake/data  #单独指定数据的目录
  process:
    thread_cnt: 10
  logging:
    config_file: ts_logger.yml
  scheduler:
    timezone: Asia/Shanghai
    background: False
    tasks:
      - default: 10 0,11,21 * * *
      - stock_basic: 0 0,11,21 * * *

tushare:
  token: #tushare api 的token，如果需要获取所有的数据，需要5000以上的积分
